### ISSUE TITLE
Looses boot parameters on upgrade

### ISSUE THREAD

**Issue by gjrtimmer** [pop-os/kernelstub#53] opened 2021-08-20 08:25 UTC
I've recently upgraded from `20.10` to `21.04`. I'm running Pop!_OS on a Clevo barebone. I had some very nice boot paramters set in my `kernelstub.conf`. They were all wiped. Unfortunately I did not have a backup of it. 

I think that a upgrade should not wipe those parameters. BTW these parameters where set at some point in time with the `kernelstub -a ...` command. Please look into this.

Also, any where, there is some upgrade backup location, where I can find my old `kernelstub.conf` ?

**Comment by isantop** [comment] 2021-08-20 15:04
I believe the upgrader does reset the boot parameters to help ensure a successful upgrade. Whether that's ideal could probably be discussed, however that is the current intended behavior.

Kernelstub itself doesn't create backups of your configuration, however some of our tools do back them up for you. The kernelstub configuration has moved from `/etc/kernelstub.conf` to `/etc/kernelstub/configuration`, and there may be additional `configuration.*` files in that directory which are backups of older configuration.

**Comment by gjrtimmer** [comment] 2021-08-23 08:28
There are not additional kernelstub config files available

I understand the decision to have the boot parameters wiped by the upgrader to ensure the successful boot, however this can also be considered problematic.

Possible Problems with the current implementation:
* boot parameters are removed which are required for successful boot (GPU params ?!?)
* boot parameters are removed which contain a lot of user config

# RFC to upgrader
* upgrader should copy current kernel config to `/etc/kernelstub/configuration-<RELEASE>`; when upgrading from `20.10` to `21.04` kernelstub config should be retained as `/etc/kernelstub/configuration-20.10` or it should be moved into a directory like `previous`. PLEASE ENSURE RELEASE VERSION NUMBER IN FILE, we do not want to override this on each upgrade.
* upgrader should provide migration wizard for boot params when preforming the upgrade
  * DEFAULT == clear boot params to retain backwards compatibility with current workflow
  * Provide options to copy over ALL params
  * Provide options to copy over selectively.

Reason for last option, very important that it is included because there is a lot of hardware out there, that require some boot option to ensure your screen works or to boot successful, and the upgrade wizard should be able to handle this.

@isantop What do you think about my proposal ?

**Comment by isantop** [comment] 2021-08-23 13:02
Sounds reasonable to me; however, I do think it's out of scope for Kernelstub and needs discussion on that repo.

**Comment by gjrtimmer** [comment] 2021-09-16 13:00
@isantop ON which repo should this discussion be ? This, parent or another ?

**Comment by isantop** [comment] 2021-09-16 16:08
The correct place for this issue is https://github.com/pop-os/upgrade

**Closed by isantop** 2021-09-16 16:08 UTC
